//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTectAI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTectAI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Predict the corresponding tectonic environment based on the whole-rock geochemical element data of your igneous rocks. 的本地化字符串。
        /// </summary>
        internal static string About_D {
            get {
                return ResourceManager.GetString("About_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANN 的本地化字符串。
        /// </summary>
        internal static string ANN_Title {
            get {
                return ResourceManager.GetString("ANN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A network composed of nodes and weighted connections inspired by biological neural networks. It includes an input layer, hidden layers, and an output layer, learning complex nonlinear relationships. 的本地化字符串。
        /// </summary>
        internal static string ANN_Title_D {
            get {
                return ResourceManager.GetString("ANN_Title_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute Configuration 的本地化字符串。
        /// </summary>
        internal static string Attribute_Config {
            get {
                return ResourceManager.GetString("Attribute_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Shutdown 的本地化字符串。
        /// </summary>
        internal static string Automatic_S_Time {
            get {
                return ResourceManager.GetString("Automatic_S_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message duration (only effective for silent notifications) 的本地化字符串。
        /// </summary>
        internal static string Automatic_S_Time_D {
            get {
                return ResourceManager.GetString("Automatic_S_Time_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tectonic Setting Mapping 的本地化字符串。
        /// </summary>
        internal static string Category_Mapping {
            get {
                return ResourceManager.GetString("Category_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Statistics 的本地化字符串。
        /// </summary>
        internal static string Data_Statistics {
            get {
                return ResourceManager.GetString("Data_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Predict 的本地化字符串。
        /// </summary>
        internal static string DataPredict {
            get {
                return ResourceManager.GetString("DataPredict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Data 的本地化字符串。
        /// </summary>
        internal static string Delete_Data {
            get {
                return ResourceManager.GetString("Delete_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid input data has been converted to 0. 的本地化字符串。
        /// </summary>
        internal static string Error_1 {
            get {
                return ResourceManager.GetString("Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please import the data. 的本地化字符串。
        /// </summary>
        internal static string Error_2 {
            get {
                return ResourceManager.GetString("Error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please proceed with the prediction first. 的本地化字符串。
        /// </summary>
        internal static string Error_3 {
            get {
                return ResourceManager.GetString("Error_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index out of bounds. 的本地化字符串。
        /// </summary>
        internal static string Error_4 {
            get {
                return ResourceManager.GetString("Error_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the input mapping... 的本地化字符串。
        /// </summary>
        internal static string Error_5 {
            get {
                return ResourceManager.GetString("Error_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The majority of input values are empty. Please check the input data. 的本地化字符串。
        /// </summary>
        internal static string Error_6 {
            get {
                return ResourceManager.GetString("Error_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export as an Excel file. 的本地化字符串。
        /// </summary>
        internal static string Export_As_Excel {
            get {
                return ResourceManager.GetString("Export_As_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File exporting... 的本地化字符串。
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This application utilizes the whole rock geochemical elements of igneous rocks to determine their tectonic settings without the need for knowledge of machine learning. You can make selections using the left-hand sidebar. 的本地化字符串。
        /// </summary>
        internal static string Home_D_1 {
            get {
                return ResourceManager.GetString("Home_D_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The distribution of the training data for the machine learning models in this application is shown in the figure below. The distinguishable tectonic setting categories are illustrated in Figure 2. 的本地化字符串。
        /// </summary>
        internal static string Home_D_2 {
            get {
                return ResourceManager.GetString("Home_D_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import File 的本地化字符串。
        /// </summary>
        internal static string Import_File {
            get {
                return ResourceManager.GetString("Import_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File loading... 的本地化字符串。
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File import has been canceled. 的本地化字符串。
        /// </summary>
        internal static string Info_1 {
            get {
                return ResourceManager.GetString("Info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integration 的本地化字符串。
        /// </summary>
        internal static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select your software language (some translations may take effect after restarting the software). 的本地化字符串。
        /// </summary>
        internal static string Languages_D {
            get {
                return ResourceManager.GetString("Languages_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Predict 的本地化字符串。
        /// </summary>
        internal static string M_Predict {
            get {
                return ResourceManager.GetString("M_Predict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping match pattern 的本地化字符串。
        /// </summary>
        internal static string Mapping_Match {
            get {
                return ResourceManager.GetString("Mapping_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In batch prediction, automatically match the Excel list names with the input element mapping schema. 的本地化字符串。
        /// </summary>
        internal static string Mapping_Match_D {
            get {
                return ResourceManager.GetString("Mapping_Match_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fuzzy mapping 的本地化字符串。
        /// </summary>
        internal static string Mapping_Match_P1 {
            get {
                return ResourceManager.GetString("Mapping_Match_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strict mapping 的本地化字符串。
        /// </summary>
        internal static string Mapping_Match_P2 {
            get {
                return ResourceManager.GetString("Mapping_Match_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machine Learning Model 的本地化字符串。
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an Appropriate Prediction Model 的本地化字符串。
        /// </summary>
        internal static string Model_D {
            get {
                return ResourceManager.GetString("Model_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Predict 的本地化字符串。
        /// </summary>
        internal static string MPrediction {
            get {
                return ResourceManager.GetString("MPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import your file for batch prediction. 的本地化字符串。
        /// </summary>
        internal static string MPrediction_D {
            get {
                return ResourceManager.GetString("MPrediction_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notification 的本地化字符串。
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Your Notification Method 的本地化字符串。
        /// </summary>
        internal static string Notification_D {
            get {
                return ResourceManager.GetString("Notification_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File Location 的本地化字符串。
        /// </summary>
        internal static string Open_File_Location {
            get {
                return ResourceManager.GetString("Open_File_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup Notification 的本地化字符串。
        /// </summary>
        internal static string PopupNotification {
            get {
                return ResourceManager.GetString("PopupNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Predict 的本地化字符串。
        /// </summary>
        internal static string Predict {
            get {
                return ResourceManager.GetString("Predict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Predicting... 的本地化字符串。
        /// </summary>
        internal static string Predicting {
            get {
                return ResourceManager.GetString("Predicting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prediction Results 的本地化字符串。
        /// </summary>
        internal static string Prediction_Res {
            get {
                return ResourceManager.GetString("Prediction_Res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open source project address 的本地化字符串。
        /// </summary>
        internal static string Project_Location {
            get {
                return ResourceManager.GetString("Project_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Dependency Support 的本地化字符串。
        /// </summary>
        internal static string Project_Support {
            get {
                return ResourceManager.GetString("Project_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Forest 的本地化字符串。
        /// </summary>
        internal static string RF_Title {
            get {
                return ResourceManager.GetString("RF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An ensemble learning method that makes predictions by constructing multiple decision trees. During training, it randomly selects samples and features, and combines the predictions of all trees using majority voting or averaging. 的本地化字符串。
        /// </summary>
        internal static string RF_Title_D {
            get {
                return ResourceManager.GetString("RF_Title_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silent Notification 的本地化字符串。
        /// </summary>
        internal static string SilentNotification {
            get {
                return ResourceManager.GetString("SilentNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Read Successfully 的本地化字符串。
        /// </summary>
        internal static string Success_1 {
            get {
                return ResourceManager.GetString("Success_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clearing Completed 的本地化字符串。
        /// </summary>
        internal static string Success_2 {
            get {
                return ResourceManager.GetString("Success_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prediction Completed 的本地化字符串。
        /// </summary>
        internal static string Success_3 {
            get {
                return ResourceManager.GetString("Success_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Exported Successfully 的本地化字符串。
        /// </summary>
        internal static string Success_4 {
            get {
                return ResourceManager.GetString("Success_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Location Opened 的本地化字符串。
        /// </summary>
        internal static string Success_5 {
            get {
                return ResourceManager.GetString("Success_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Your Software Theme 的本地化字符串。
        /// </summary>
        internal static string Theme_D {
            get {
                return ResourceManager.GetString("Theme_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Predict 的本地化字符串。
        /// </summary>
        internal static string UPrediction {
            get {
                return ResourceManager.GetString("UPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Your Data for Single Prediction. 的本地化字符串。
        /// </summary>
        internal static string UPrediction_D {
            get {
                return ResourceManager.GetString("UPrediction_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version： 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whole-Rock Major Elements 的本地化字符串。
        /// </summary>
        internal static string WholeRock_ME {
            get {
                return ResourceManager.GetString("WholeRock_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Major chemical elements of igneous rocks. 的本地化字符串。
        /// </summary>
        internal static string WholeRock_ME_D {
            get {
                return ResourceManager.GetString("WholeRock_ME_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whole-Rock Trace Elements 的本地化字符串。
        /// </summary>
        internal static string WholeRock_TE {
            get {
                return ResourceManager.GetString("WholeRock_TE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trace chemical elements of igneous rocks. 的本地化字符串。
        /// </summary>
        internal static string WholeRock_TE_D {
            get {
                return ResourceManager.GetString("WholeRock_TE_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XGBoost 的本地化字符串。
        /// </summary>
        internal static string XGB_Title {
            get {
                return ResourceManager.GetString("XGB_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An efficient implementation of the gradient boosting algorithm. It incrementally adds new weak learners (typically decision trees), focusing on reducing prediction errors and improving model accuracy. 的本地化字符串。
        /// </summary>
        internal static string XGB_Title_D {
            get {
                return ResourceManager.GetString("XGB_Title_D", resourceCulture);
            }
        }
    }
}
